# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import ppconsumer_pb2 as ppconsumer__pb2


class ConsumerServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateConsumer = channel.unary_unary(
        '/ppconsumer.ConsumerService/CreateConsumer',
        request_serializer=ppconsumer__pb2.Consumer.SerializeToString,
        response_deserializer=ppconsumer__pb2.Consumer.FromString,
        )
    self.UpdateConsumer = channel.unary_unary(
        '/ppconsumer.ConsumerService/UpdateConsumer',
        request_serializer=ppconsumer__pb2.Consumer.SerializeToString,
        response_deserializer=ppconsumer__pb2.Consumer.FromString,
        )
    self.GetConsumer = channel.unary_unary(
        '/ppconsumer.ConsumerService/GetConsumer',
        request_serializer=ppconsumer__pb2.ConsumerRequest.SerializeToString,
        response_deserializer=ppconsumer__pb2.Consumer.FromString,
        )
    self.DeleteConsumer = channel.unary_unary(
        '/ppconsumer.ConsumerService/DeleteConsumer',
        request_serializer=ppconsumer__pb2.ConsumerRequest.SerializeToString,
        response_deserializer=ppconsumer__pb2.Response.FromString,
        )


class ConsumerServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CreateConsumer(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateConsumer(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetConsumer(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteConsumer(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ConsumerServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateConsumer': grpc.unary_unary_rpc_method_handler(
          servicer.CreateConsumer,
          request_deserializer=ppconsumer__pb2.Consumer.FromString,
          response_serializer=ppconsumer__pb2.Consumer.SerializeToString,
      ),
      'UpdateConsumer': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateConsumer,
          request_deserializer=ppconsumer__pb2.Consumer.FromString,
          response_serializer=ppconsumer__pb2.Consumer.SerializeToString,
      ),
      'GetConsumer': grpc.unary_unary_rpc_method_handler(
          servicer.GetConsumer,
          request_deserializer=ppconsumer__pb2.ConsumerRequest.FromString,
          response_serializer=ppconsumer__pb2.Consumer.SerializeToString,
      ),
      'DeleteConsumer': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteConsumer,
          request_deserializer=ppconsumer__pb2.ConsumerRequest.FromString,
          response_serializer=ppconsumer__pb2.Response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ppconsumer.ConsumerService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
